### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by InnaBlack** [ByteriX/Localinter#1]
I have done this "Add to "Build Phases" run script:
${SRCROOT}/Localinter.swift"

**Comment by sofbix** [comment]
Do you copy to Project directory Localinter.swift file?
Can you go to the SRCROOT directory from command line and run
"Localinter.swift"?

**Comment by InnaBlack** [comment]
It works ! Maybe after chmod u+x Localinter.swift

**Comment by sofbix** [comment]
Congratulation :) and Thanks for comments, it can help other developers
