### ISSUE TITLE
Do you have any demo project to explore?

### ISSUE THREAD

**Issue by pitt500** [ByteriX/Localinter#2]
Hi @sofbix, I just found your repo exploring alternatives to catch localizable string issues and your script looks great!

However, I have some issues working with it. For example I have this SwiftUI code:
```swift
struct ContentView: View {
    var body: some View {
        VStack {
            Text("text_1")
            Text("text_2")
            Text("text_3")
            Text("text_4")
            Text("text_5")
        }
        .padding()
    }
}
```

And these localized strings:

```swift
"text_1" = "Hola 1";
"text_2" = "Hola 2";
"text_3" = "Hola 3";
"text_4" = "Hola 4";
"text_5" = "Hola 5";
```

Following your setup, when I compile the code I got the following errors:

`[Unused cases] text_1 is not used from code`
`[Unused cases] text_2 is not used from code`
`[Unused cases] text_3 is not used from code`
`[Unused cases] text_4 is not used from code`
`[Unused cases] text_5 is not used from code`

And I don't have idea why if they are in the code and I'm pointing the `relativeSourcePath` to the source code.

Do you have any example that you could share to compare and use your script?

Thanks in advance,
Pitt

**Comment by sofbix** [comment]
Hi @pitt500, thanks for comming and issue.
My script just didn't support SwiftUI, but in 1.2 I added this supporting.
Yes, I have Example and added to repo.
Please write if you have questions.

**Comment by pitt500** [comment]
Thank you very much!
