### ISSUE TITLE
A lot of unsed cases

### ISSUE THREAD

**Issue by Spikepiegel** [ByteriX/Localinter#3]
Hello, I want to intergrate Localinter library into our project, but I catch a lot of compiling error like this:
[Unused cases] general.all is not used from code
<img width="476" alt="Снимок экрана 2023-08-04 в 23 08 01" src="https://github.com/ByteriX/Localinter/assets/115900769/460d7f5a-2741-4658-b18b-f4cc95ab344e">

This image shows current code on Localinter.swift

let relativeLocalizablePath = "/Targets/UpTown/Resources"
is a path to Localizable.string file

let relativeSourcePath = "/Derived/Sources"
is a path to files with enums which are generated by SwiftGen

<img width="1030" alt="Снимок экрана 2023-08-04 в 23 08 33" src="https://github.com/ByteriX/Localinter/assets/115900769/bdb1eab3-1821-49a1-9f90-9679f9ab1cb9">

maybe     .swiftGen(enumName: #"UptownStrings\.Localizable"#) incorrect?
<img width="280" alt="Снимок экрана 2023-08-04 в 23 10 54" src="https://github.com/ByteriX/Localinter/assets/115900769/2009b4b5-1d4c-41ef-aab9-5325e832476d">

**Comment by Spikepiegel** [comment]
<img width="656" alt="Снимок экрана 2023-08-05 в 00 45 49" src="https://github.com/ByteriX/Localinter/assets/115900769/0fd58620-6fda-4c90-894d-9a96da25ae50">

if change masterKeys property on usedKeys on the 443 line it works correctly
<img width="780" alt="Снимок экрана 2023-08-05 в 00 53 42" src="https://github.com/ByteriX/Localinter/assets/115900769/1a9e7f2e-e801-4c03-bdc3-f4121051291d">

**Comment by sofbix** [comment]
Hi, thanks a lot for issue.
So,  How did you set up SwiftGen? Please show me yaml settings. 

> is a path to files with enums which are generated by SwiftGen

You made mistake: you need set up relativeSourcePath to sources with using values from enums which are generated by SwiftGen. Otherwise the checking wouldn't make any sense

> if change masterKeys property on usedKeys on the 443 line it works correctly

You had made some thing like that:
unused = used - used
Then we have unused == Empty  and now errors don't raise

**Comment by Spikepiegel** [comment]
sorry, I haven't got about relativeSourcePath
TuistStrings+Uptown, TuistStrings+UpTownCore, etc. files with my enums, and choosed Source folder as value for relativeSourcePath

**Comment by sofbix** [comment]
So, did you change relativeSourcePath?
That helped?

**Comment by Spikepiegel** [comment]
yes, it works, thank
you

**Comment by sofbix** [comment]
you're welcome
