### ISSUE TITLE
Интеграция Localinter c tuist

### ISSUE THREAD

**Issue by djud17** [ByteriX/Localinter#4]
Сергей, здравствуйте!
Пытаемся интегрировать ваш линтер в проект, проект на туисте. Не получается правильно настроить линтер, возможно, ошибка в названии enum? Глобальный сгенерированный enum называется UpTownStrings, остальные дочерние для модулей. Нужно ли как то указывать путь до него, если enum лежит не в корневой папке?

При попытке запуска линтера - ошибка на каждое значение "unused" + на некоторые ругается в связи с отсутствием перевода.

relativeLocalizablePath - путь до папки внутри которой файлы локализации
relativeSourcePath - путь до папки внутри которой исходники .swift сгруппированные по папкам

![image](https://github.com/ByteriX/Localinter/assets/24828568/ac70096b-db96-46c4-a8a6-34b7b2f0b126)
![image](https://github.com/ByteriX/Localinter/assets/24828568/49eb048f-b6cc-4994-9892-8da24d86cf26)

**Comment by sofbix** [comment]
Привет, Давид.
А в какую константу сгенерировал SwiftGen например "general.all", было бы круто, если бы вы показали кусок исходника где используете эту сгенерированную константу, она лежит надеюсь в подкаталогах папки /UpTown/Sources?

**Comment by djud17** [comment]
Нет, сгенерированные файлы лежат в корне, в папке Derrived. 
![image](https://github.com/ByteriX/Localinter/assets/24828568/31dd81eb-304c-4c09-b2dd-e29085c15ee8)

Вот результат генерации
![image](https://github.com/ByteriX/Localinter/assets/24828568/9168b22b-d10f-4f63-aa75-d7215f81f6b2)

**Comment by sofbix** [comment]
меня интересует не куда сгенерирована константа, а где она применяется, выше писал:

"кусок исходника где используете эту сгенерированную константу"

**Comment by sofbix** [comment]
используемый исходник должен лежать в этой папке

**Comment by djud17** [comment]
![image](https://github.com/ByteriX/Localinter/assets/24828568/25458d7b-545b-44b0-aed6-ba10284425c4)
![image](https://github.com/ByteriX/Localinter/assets/24828568/d45468bd-1ab8-479c-8706-4744c0e1f1e9)

**Comment by sofbix** [comment]
Проблема в том, что локалинтр чувствителен к регистру, Swiftgen сгенерировал
из "general.all" константу "UpTownStrings.General.all", потому что SwiftGen нельзя иначе настроить:

согласно натациям enum должен именоваться с большой буквы, соответственно general переименовывает в General.

Чтобы линтр понял что творит SwiftGen, мы в файлах строк переименовывали все константы, чтобы их название полностью соответствовало сгенерированным ключам, в вашем случае должно быть:

`"General.all" = "All";` вместо `"general.all" = "All";`

Скажите, насколько это для вас приемлемо?

Идея автопереименовывания была у меня, но поскольку и сам SwiftGen можно настроить по разному и в реальности констатнты можно назвать по разному, решил не реализоывать автопереименовывание

**Comment by sofbix** [comment]
поскольку не раз уже тут допускают ошибку, прокоментировал в скрипте использования этого паттерна регулярок

**Comment by sofbix** [comment]
Как дела? Получилось завести или какие то трудности все же возникли?

**Comment by djud17** [comment]
Да, все получилось, после того как переименовали ключи, как вы сказали
